DROP TABLE IF EXISTS TRANSACTIONS;

CREATE TABLE TRANSACTIONS(
    TRANSACTION_ID          LONG                AUTO_INCREMENT  PRIMARY KEY,
    TRANSACTION_DATE        DATE                NOT NULL,
    ACCOUNT_NUMBER          VARCHAR(50 CHAR)    NOT NULL,
    CURRENCY                VARCHAR(10 CHAR)    NOT NULL,
    CREDIT                  BOOLEAN             NOT NULL,
    AMOUNT                  DECIMAL             NOT NULL,
    COUNTER_ACCOUNT_NAME    VARCHAR(255 CHAR),
    COUNTER_ACCOUNT_NUMBER  VARCHAR(255 CHAR),
    DESCRIPTION             VARCHAR(255 CHAR),
);

INSERT INTO TRANSACTIONS(
    ACCOUNT_NUMBER,
    CURRENCY,
    CREDIT,
    AMOUNT,
    COUNTER_ACCOUNT_NAME,
    COUNTER_ACCOUNT_NUMBER,
    DESCRIPTION
) VALUES (
      CURRENT_DATE(),
      'NL72RABO0102453942',
      'EUR',
      TRUE,
      234.21,
      'S. Anker',
      'NL72RABO0102453942',
      'This is a transaction'
);
